"""Update games table

Revision ID: 1444bc6bd0cb
Revises: 60e03a821c7f
Create Date: 2025-03-25 15:16:39.782084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1444bc6bd0cb'
down_revision = '60e03a821c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_build', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('web_build')

    # ### end Alembic commands ###
