"""Update game table

Revision ID: 574022d2c33a
Revises: 5fdae3ee6326
Create Date: 2025-03-19 11:52:52.615975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574022d2c33a'
down_revision = '5fdae3ee6326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_file_path', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('game_file_path')

    # ### end Alembic commands ###
