"""Update game table

Revision ID: 7de7df28016e
Revises: 16776917996a
Create Date: 2025-03-17 13:36:25.186369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de7df28016e'
down_revision = '16776917996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('tagline')

    # ### end Alembic commands ###
