"""Update filepath columns to url

Revision ID: 7fdcf9540d91
Revises: e3121d62f103
Create Date: 2025-03-20 21:50:20.471822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdcf9540d91'
down_revision = 'e3121d62f103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=256), nullable=False))
        batch_op.drop_column('cover_filepath')

    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=256), nullable=False))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=256), nullable=False))
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=256), nullable=False))
        batch_op.alter_column('size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('url')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_filepath', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
