"""Create screenshots table

Revision ID: e3121d62f103
Revises: 8684fa4b2ae3
Create Date: 2025-03-19 17:31:46.097604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3121d62f103'
down_revision = '8684fa4b2ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=256), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshot_game_id'), ['game_id'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_filepath', sa.String(length=256), nullable=False))

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('cover_filepath')

    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshot_game_id'))

    op.drop_table('screenshot')
    # ### end Alembic commands ###
